site_name: HistoPath
repo_url: https://github.com/RationAI/histopath

nav:
  - Home: index.md
  - Learn:
      - GET STARTED:
          - Quick Start:
              - learn/get-started/quick-start/index.md
              - learn/get-started/quick-start/tiling.md
          - learn/get-started/installation.md
  - Reference:
      - Tiling:
          - annotations: reference/tiling/annotations.md
          - read_slide_tile: reference/tiling/read_slide_tile.md
          - tilers: reference/tiling/tilers.md
          - utils: reference/tiling/utils.md
      - Parsers:
          - ASAPParser: reference/parsers/asap.md
          - GeoJSONParser: reference/parsers/geojson.md
      - Augmentations:
          - estimate_stain_vectors: reference/augmentations/estimate_stain_vectors.md
          - StainAugmentor: reference/augmentations/stain_augmentor.md
      - Ray:
          - SlideMetaDatasource: reference/ray/slide_metadatasource.md
          - VipsTiffDatasink: reference/ray/vips_tiff_datasink.md
      - Openslide: reference/openslide.md
      - Utils: reference/utils.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra:
  version:
    provider: mike
