name: Lint
on: workflow_dispatch
permissions:
  contents: read

jobs:
  lint:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install dependencies (ruff)
        run: pip install ruff

      - name: Run ruff check
        run: ruff check --no-fix -n

      - name: Run ruff format check
        run: ruff format --check -n

  mypy:
    name: MyPy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --dev

      - name: Run MyPy
        run: uv run mypy .
